/anytraverse:
  ros__parameters:
    hydra_config_file: src/config/pipelines/paper.yaml
    scene_sim_thresh: 0.8
    roi_unc_thresh: 0.5
    roi_x_bounds:
      - 0.33
      - 0.67
    roi_y_bounds:
      - 0.67
      - 0.95
