anytraverse:
  ros__parameters:
    hydra_config_file: config/pipelines/paper.yaml
    scene_sim_thresh: 0.8
    roi_unc_thresh: 0.5
    roi_x_bounds:
      - 0.33
      - 0.67
    roi_y_bounds:
      - 0.67
      - 0.95
    topic:
      image: /camera/rgb/image_raw
      trav_map: trav_map
      unc_map: unc_map
      state: state

vel_gating:
  ros__parameters:
    enable: true
    state_topic: state
    cmd_vel_topic:
      in: /cmd_vel
      out: /cmd_vel_gated
